/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.28                          *
*        Compiled Jan 30 2015, 16:41:06                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER Æô (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "includes.h"
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0 (GUI_ID_USER + 0x00)

#define ID_TEXT_0 (GUI_ID_USER + 0x01)
#define ID_TEXT_1 (GUI_ID_USER + 0x02)
#define ID_TEXT_2 (GUI_ID_USER + 0x03)
#define ID_BUTTON_0 (GUI_ID_USER + 0x04)
#define ID_BUTTON_1 (GUI_ID_USER + 0x06)
#define ID_CHECKBOX_0 (GUI_ID_USER + 0x07)
#define ID_CHECKBOX_1 (GUI_ID_USER + 0x08)
#define ID_BUTTON_2 (GUI_ID_USER + 0x09)
#define ID_BUTTON_3 (GUI_ID_USER + 0x0A)

//2å?
#define ID_TEXT_3 (GUI_ID_USER + 0x0B)
#define ID_TEXT_4 (GUI_ID_USER + 0x0C)

#define ID_BUTTON_4 (GUI_ID_USER + 0x0D)
#define ID_BUTTON_5 (GUI_ID_USER + 0x0E)
#define ID_BUTTON_6 (GUI_ID_USER + 0x0F)
#define ID_BUTTON_7 (GUI_ID_USER + 0x10)

#define ID_CHECKBOX_2 (GUI_ID_USER + 0x11)
#define ID_CHECKBOX_3 (GUI_ID_USER + 0x12)

//3å?
#define ID_TEXT_5 (GUI_ID_USER + 0x13)
#define ID_TEXT_6 (GUI_ID_USER + 0x14)

#define ID_BUTTON_8 (GUI_ID_USER + 0x15)
#define ID_BUTTON_9 (GUI_ID_USER + 0x016)
#define ID_BUTTON_10 (GUI_ID_USER + 0x17)
#define ID_BUTTON_11 (GUI_ID_USER + 0x18)

#define ID_CHECKBOX_4 (GUI_ID_USER + 0x19)
#define ID_CHECKBOX_5 (GUI_ID_USER + 0x1A)

//4å?
#define ID_TEXT_7 (GUI_ID_USER + 0x1B)
#define ID_TEXT_8 (GUI_ID_USER + 0x1C)

#define ID_BUTTON_12 (GUI_ID_USER + 0x1D)
#define ID_BUTTON_13 (GUI_ID_USER + 0x1E)
#define ID_BUTTON_14 (GUI_ID_USER + 0x1F)
#define ID_BUTTON_15 (GUI_ID_USER + 0x20)

#define ID_CHECKBOX_6 (GUI_ID_USER + 0x21)
#define ID_CHECKBOX_7 (GUI_ID_USER + 0x22)

//5å?
#define ID_TEXT_9 (GUI_ID_USER + 0x23)
#define ID_TEXT_10 (GUI_ID_USER + 0x24)

#define ID_BUTTON_16 (GUI_ID_USER + 0x25)
#define ID_BUTTON_17 (GUI_ID_USER + 0x26)
#define ID_BUTTON_18 (GUI_ID_USER + 0x27)
#define ID_BUTTON_19 (GUI_ID_USER + 0x28)

#define ID_CHECKBOX_8 (GUI_ID_USER + 0x29)
#define ID_CHECKBOX_9 (GUI_ID_USER + 0x2A)

//6å?
#define ID_TEXT_11 (GUI_ID_USER + 0x2B)
#define ID_TEXT_12 (GUI_ID_USER + 0x2C)

#define ID_BUTTON_20 (GUI_ID_USER + 0x2D)
#define ID_BUTTON_21 (GUI_ID_USER + 0x2E)
#define ID_BUTTON_22 (GUI_ID_USER + 0x2F)
#define ID_BUTTON_23 (GUI_ID_USER + 0x30)

#define ID_CHECKBOX_10 (GUI_ID_USER + 0x31)
#define ID_CHECKBOX_11 (GUI_ID_USER + 0x32)

//7å?
#define ID_TEXT_13 (GUI_ID_USER + 0x33)
#define ID_TEXT_14 (GUI_ID_USER + 0x34)

#define ID_BUTTON_24 (GUI_ID_USER + 0x35)
#define ID_BUTTON_25 (GUI_ID_USER + 0x36)
#define ID_BUTTON_26 (GUI_ID_USER + 0x37)
#define ID_BUTTON_27 (GUI_ID_USER + 0x38)

#define ID_CHECKBOX_12 (GUI_ID_USER + 0x39)
#define ID_CHECKBOX_13 (GUI_ID_USER + 0x3A)
//add
/*é€Ÿåº¦æ˜¾ç¤ºEDITæŽ§ä»¶*/
//1å?
#define ID_EDIT_1 (GUI_ID_USER + 0x3B)
#define ID_EDIT_2 (GUI_ID_USER + 0x3C)
//2å?
#define ID_EDIT_3 (GUI_ID_USER + 0x3D)
#define ID_EDIT_4 (GUI_ID_USER + 0x3E)
//3å?
#define ID_EDIT_5 (GUI_ID_USER + 0x3F)
#define ID_EDIT_6 (GUI_ID_USER + 0x40)
//4å?
#define ID_EDIT_7 (GUI_ID_USER + 0x41)
#define ID_EDIT_8 (GUI_ID_USER + 0x42)
//5å?
#define ID_EDIT_9 (GUI_ID_USER + 0x43)
#define ID_EDIT_10 (GUI_ID_USER + 0x44)
//6å?
#define ID_EDIT_11 (GUI_ID_USER + 0x45)
#define ID_EDIT_12 (GUI_ID_USER + 0x46)
//7å?
#define ID_EDIT_13 (GUI_ID_USER + 0x47)
#define ID_EDIT_14 (GUI_ID_USER + 0x48)
/***è¿”å›žä¸»èœå•æŒ‰é’?**/
#define ID_BUTTON_28 (GUI_ID_USER + 0x49)

/***ç”µæœºå·æ˜¾ç¤?**/
//1å?
#define ID_TEXT_15 (GUI_ID_USER + 0x4A)
//2å?
#define ID_TEXT_16 (GUI_ID_USER + 0x4B)
//3å?
#define ID_TEXT_17 (GUI_ID_USER + 0x4C)
//4å?
#define ID_TEXT_18 (GUI_ID_USER + 0x4D)
//5å?
#define ID_TEXT_19 (GUI_ID_USER + 0x4E)
//6å?
#define ID_TEXT_20 (GUI_ID_USER + 0x4F)
//7å?
#define ID_TEXT_21 (GUI_ID_USER + 0x50)
/*æ°”ç¼¸1*/
#define ID_BUTTON_29 (GUI_ID_USER + 0x51)
#define ID_BUTTON_30 (GUI_ID_USER + 0x52)
#define ID_TEXT_31 (GUI_ID_USER + 0x53)
/*æ°”ç¼¸2*/
#define ID_BUTTON_31 (GUI_ID_USER + 0x54)
#define ID_BUTTON_32 (GUI_ID_USER + 0x55)
#define ID_TEXT_32 (GUI_ID_USER + 0x56)



// USER Æô (Optionally insert additional defines)
#define Right_move_step 160
#define Down_move_step 170

// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER Æô (Optionally insert additional static data)
// USER END
static const GUI_WIDGET_CREATE_INFO MotorcontrolWindow_aDialogCreate[] = {

  { WINDOW_CreateIndirect, "ar_MotorcontrolWindow", ID_WINDOW_0, 0, 0, 800, 480, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "1ºÅÉú²úÏßµ÷ÊÔ½çÃæ", ID_TEXT_0, 0, 0, 800, 30, 0, 0x0, 0 },
  //1å?
  { TEXT_CreateIndirect, "Ä¿±êËÙ¶È", ID_TEXT_1, 10, 90, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "µ±Ç°ËÙ¶È", ID_TEXT_2, 10, 130, 80, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "ËÙ¶È+", ID_BUTTON_0, 20, 180, 50, 24, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "ËÙ¶È-", ID_BUTTON_1, 95, 180, 50, 24, 0, 0x0, 0 },
  { CHECKBOX_CreateIndirect, "·´×ª", ID_CHECKBOX_0, 20, 219, 70, 24, 0, 0x0, 0 },
  { CHECKBOX_CreateIndirect, "Õý×ª", ID_CHECKBOX_1, 95, 219, 55, 24, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Æô", ID_BUTTON_2, 110, 90, 30, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Í£", ID_BUTTON_3, 110, 130, 30, 20, 0, 0x0, 0 },

  //2å?
  { TEXT_CreateIndirect, "Ä¿±êËÙ¶È", ID_TEXT_3, 10 + Right_move_step, 90, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "µ±Ç°ËÙ¶È", ID_TEXT_4, 10 + Right_move_step, 130, 80, 20, 0, 0x0, 0 },

  { BUTTON_CreateIndirect, "ËÙ¶È+", ID_BUTTON_4, 20 + Right_move_step, 180, 50, 24, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "ËÙ¶È-", ID_BUTTON_5, 95 + Right_move_step, 180, 50, 24, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Æô", ID_BUTTON_6, 110 + Right_move_step, 90, 30, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Í£", ID_BUTTON_7, 110 + Right_move_step, 130, 30, 20, 0, 0x0, 0 },

  { CHECKBOX_CreateIndirect, "·´×ª", ID_CHECKBOX_2, 20 + Right_move_step, 219, 70, 24, 0, 0x0, 0 },
  { CHECKBOX_CreateIndirect, "Õý×ª", ID_CHECKBOX_3, 95 + Right_move_step, 219, 55, 24, 0, 0x0, 0 },

  //3å?
  { TEXT_CreateIndirect, "Ä¿±êËÙ¶È", ID_TEXT_5, 10 + Right_move_step * 2, 90, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "µ±Ç°ËÙ¶È", ID_TEXT_6, 10 + Right_move_step * 2, 130, 80, 20, 0, 0x0, 0 },

  { BUTTON_CreateIndirect, "ËÙ¶È+", ID_BUTTON_8, 20 + Right_move_step * 2, 180, 50, 24, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "ËÙ¶È-", ID_BUTTON_9, 95 + Right_move_step * 2, 180, 50, 24, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Æô", ID_BUTTON_10, 110 + Right_move_step * 2, 90, 30, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Í£", ID_BUTTON_11, 110 + Right_move_step * 2, 130, 30, 20, 0, 0x0, 0 },

  { CHECKBOX_CreateIndirect, "·´×ª", ID_CHECKBOX_4, 20 + Right_move_step * 2, 219, 70, 24, 0, 0x0, 0 },
  { CHECKBOX_CreateIndirect, "Õý×ª", ID_CHECKBOX_5, 95 + Right_move_step * 2, 219, 55, 24, 0, 0x0, 0 },

  //4å?
  { TEXT_CreateIndirect, "Ä¿±êËÙ¶È", ID_TEXT_7, 10 + Right_move_step * 3, 90, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "µ±Ç°ËÙ¶È", ID_TEXT_8, 10 + Right_move_step * 3, 130, 80, 20, 0, 0x0, 0 },

  { BUTTON_CreateIndirect, "ËÙ¶È+", ID_BUTTON_12, 20 + Right_move_step * 3, 180, 50, 24, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "ËÙ¶È-", ID_BUTTON_13, 95 + Right_move_step * 3, 180, 50, 24, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Æô", ID_BUTTON_14, 110 + Right_move_step * 3, 90, 30, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Í£", ID_BUTTON_15, 110 + Right_move_step * 3, 130, 30, 20, 0, 0x0, 0 },

  { CHECKBOX_CreateIndirect, "·´×ª", ID_CHECKBOX_6, 20 + Right_move_step * 3, 219, 70, 24, 0, 0x0, 0 },
  { CHECKBOX_CreateIndirect, "Õý×ª", ID_CHECKBOX_7, 95 + Right_move_step * 3, 219, 55, 24, 0, 0x0, 0 },

  //5å?
  { TEXT_CreateIndirect, "Ä¿±êËÙ¶È", ID_TEXT_9, 10 + Right_move_step * 4, 90, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "µ±Ç°ËÙ¶È", ID_TEXT_10, 10 + Right_move_step * 4, 130, 80, 20, 0, 0x0, 0 },

  { BUTTON_CreateIndirect, "ËÙ¶È+", ID_BUTTON_16, 20 + Right_move_step * 4, 180, 50, 24, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "ËÙ¶È-", ID_BUTTON_17, 95 + Right_move_step * 4, 180, 50, 24, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Æô", ID_BUTTON_18, 110 + Right_move_step * 4, 90, 30, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Í£", ID_BUTTON_19, 110 + Right_move_step * 4, 130, 30, 20, 0, 0x0, 0 },

  { CHECKBOX_CreateIndirect, "·´×ª", ID_CHECKBOX_8, 20 + Right_move_step * 4, 219, 70, 24, 0, 0x0, 0 },
  { CHECKBOX_CreateIndirect, "Õý×ª", ID_CHECKBOX_9, 95 + Right_move_step * 4, 219, 55, 24, 0, 0x0, 0 },

  //6å?
  { TEXT_CreateIndirect, "Ä¿±êËÙ¶È", ID_TEXT_11, 10, 90 + Down_move_step, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "µ±Ç°ËÙ¶È", ID_TEXT_12, 10, 130 + Down_move_step, 80, 20, 0, 0x0, 0 },

  { BUTTON_CreateIndirect, "ËÙ¶È+", ID_BUTTON_20, 20, 180 + Down_move_step, 50, 24, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "ËÙ¶È-", ID_BUTTON_21, 95, 180 + Down_move_step, 50, 24, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Æô", ID_BUTTON_22, 110, 90 + Down_move_step, 30, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Í£", ID_BUTTON_23, 110, 130 + Down_move_step, 30, 20, 0, 0x0, 0 },

  { CHECKBOX_CreateIndirect, "·´×ª", ID_CHECKBOX_10, 20, 219 + Down_move_step, 70, 24, 0, 0x0, 0 },
  { CHECKBOX_CreateIndirect, "Õý×ª", ID_CHECKBOX_11, 95, 219 + Down_move_step, 55, 24, 0, 0x0, 0 },

  //7å?
  { TEXT_CreateIndirect, "Ä¿±êËÙ¶È", ID_TEXT_13, 10 + Right_move_step, 90 + Down_move_step, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "µ±Ç°ËÙ¶È", ID_TEXT_14, 10 + Right_move_step, 130 + Down_move_step, 80, 20, 0, 0x0, 0 },

  { BUTTON_CreateIndirect, "ËÙ¶È+", ID_BUTTON_24, 20 + Right_move_step, 180 + Down_move_step, 50, 24, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "ËÙ¶È-", ID_BUTTON_25, 95 + Right_move_step, 180 + Down_move_step, 50, 24, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Æô", ID_BUTTON_26, 110 + Right_move_step, 90 + Down_move_step, 30, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Í£", ID_BUTTON_27, 110 + Right_move_step, 130 + Down_move_step, 30, 20, 0, 0x0, 0 },

  { CHECKBOX_CreateIndirect, "·´×ª", ID_CHECKBOX_12, 20 + Right_move_step, 219 + Down_move_step, 70, 24, 0, 0x0, 0 },
  { CHECKBOX_CreateIndirect, "Õý×ª", ID_CHECKBOX_13, 95 + Right_move_step, 219 + Down_move_step, 55, 24, 0, 0x0, 0 },
  //add
  /*é€Ÿåº¦æ˜¾ç¤ºEDITæŽ§ä»¶*/
  //1å?
  { EDIT_CreateIndirect, "DspeedEdit", ID_EDIT_1, 10, 110, 34, 20, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "SspeedEdit", ID_EDIT_2, 10, 150, 34, 20, 0, 0x64, 0 },
  //2å?
  { EDIT_CreateIndirect, "DspeedEdit", ID_EDIT_3, 10 + Right_move_step, 110, 34, 20, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "SspeedEdit", ID_EDIT_4, 10 + Right_move_step, 150, 34, 20, 0, 0x64, 0 },
  //3å?
  { EDIT_CreateIndirect, "DspeedEdit", ID_EDIT_5, 10 + Right_move_step * 2, 110, 34, 20, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "SspeedEdit", ID_EDIT_6, 10 + Right_move_step * 2, 150, 34, 20, 0, 0x64, 0 },
  //4å?
  { EDIT_CreateIndirect, "DspeedEdit", ID_EDIT_7, 10 + Right_move_step * 3, 110, 34, 20, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "SspeedEdit", ID_EDIT_8, 10 + Right_move_step * 3, 150, 34, 20, 0, 0x64, 0 },
  //5å?
  { EDIT_CreateIndirect, "DspeedEdit", ID_EDIT_9, 10 + Right_move_step * 4, 110, 34, 20, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "SspeedEdit", ID_EDIT_10, 10 + Right_move_step * 4, 150, 34, 20, 0, 0x64, 0 },
  //6å?
  { EDIT_CreateIndirect, "DspeedEdit", ID_EDIT_11, 10, 110 + Down_move_step, 34, 20, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "SspeedEdit", ID_EDIT_12, 10, 150 + Down_move_step, 34, 20, 0, 0x64, 0 },
  //7å?
  { EDIT_CreateIndirect, "DspeedEdit", ID_EDIT_13, 10 + Right_move_step, 110 + Down_move_step, 34, 20, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "SspeedEdit", ID_EDIT_14, 10 + Right_move_step, 150 + Down_move_step, 34, 20, 0, 0x64, 0 },

  /***è¿”å›žä¸»èœå•æŒ‰é’?**/
  { BUTTON_CreateIndirect, "·µ»Ø", ID_BUTTON_28, 710, 5, 80, 30, 0, 0x0, 0 },

  /***ç”µæœºå·æ˜¾ç¤?**/
  //1å?
  { TEXT_CreateIndirect, "µç»ú1", ID_TEXT_15, 50, 65, 80, 20, 0, 0x0, 0 },
  //2å?
  { TEXT_CreateIndirect, "µç»ú2", ID_TEXT_16, 50 + Right_move_step, 65, 80, 20, 0, 0x0, 0 },
  //3å?
  { TEXT_CreateIndirect, "µç»ú3", ID_TEXT_17, 50 + Right_move_step*2, 65, 80, 20, 0, 0x0, 0 },
  //4å?
  { TEXT_CreateIndirect, "µç»ú4", ID_TEXT_18, 50 + Right_move_step*3, 65, 80, 20, 0, 0x0, 0 },
  //5å?
  { TEXT_CreateIndirect, "µç»ú5", ID_TEXT_19, 50 + Right_move_step*4, 65, 80, 20, 0, 0x0, 0 },
  //6å?
  { TEXT_CreateIndirect, "µç»ú6", ID_TEXT_20, 50, 75+Down_move_step*2, 80, 20, 0, 0x0, 0 },
  //7å?
  { TEXT_CreateIndirect, "µç»ú7", ID_TEXT_21, 50 + Right_move_step, 75 + Down_move_step*2, 80, 20, 0, 0x0, 0 },

  /**æ°”ç¼¸**/
  //1
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_29, 10+10 + Right_move_step * 2, 45 +85+ Down_move_step, 50, 25, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_30, 80+10 + Right_move_step * 2, 45 +85+ Down_move_step, 50, 25, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Æø¸×1", ID_TEXT_31, 28 +10+ Right_move_step * 2, 13 +85+ Down_move_step, 80, 20, 0, 0x0, 0 },
  //2
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_31, 10 + 10 + Right_move_step * 2, 45 + 85*2 + Down_move_step, 50, 25, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_32, 80 + 10 + Right_move_step * 2, 45 + 85*2 + Down_move_step, 50, 25, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Æø¸×2", ID_TEXT_32, 28 + 10 + Right_move_step * 2, 13 + 85*2 + Down_move_step, 80, 20, 0, 0x0, 0 },



  // USER Æô (Optionally insert additional widgets)
  // USER END
};


/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

char sw_flag23 = 3;
char sw_flag67 = 7;
char sw_flag1011 = 11;
char sw_flag1415 = 15;
char sw_flag1819 = 19;
char sw_flag2223 = 23;
char sw_flag2627 = 27;
char sw_flag2930 = 30;
char sw_flag3132 = 32;
char ar_fuwei_zhengfan = 0;
static int _ar_Key[] = { GUI_KEY_UP, GUI_KEY_DOWN, GUI_KEY_SPACE, GUI_KEY_ENTER};
extern char switchSpeed;
// USER Æô (Optionally insert additional static code)
/*********************************************************************
*
*       _cbButton2
*
**********************************************************************
*/
static void _cbButton2(WM_MESSAGE * pMsg) //--------------ï¼?ï¼?
{


	GUI_RECT Rect;


	switch (pMsg->MsgId)
	{
	case WM_PAINT:
		WM_GetClientRect(&Rect);

		if (sw_flag23 == 2)//if (BUTTON_IsPressed(hWin))
		{
			GUI_SetColor(GUI_GREEN);
			GUI_FillRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);
			GUI_SetBkColor(GUI_GREEN);
			GUI_SetColor(GUI_BLACK);
			GUI_SetFont(&GUI_FontHZ16);
			GUI_DispStringInRect("Æô", &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);

		}
		if (sw_flag23!=2)
		{

			GUI_SetColor(GUI_LIGHTGRAY);
			GUI_FillRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);
			GUI_SetBkColor(GUI_LIGHTGRAY);

			GUI_SetColor(GUI_BLACK);
			GUI_SetPenSize(1);
			GUI_DrawRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);

			GUI_SetColor(GUI_BLACK);
			GUI_SetFont(&GUI_FontHZ16);
			GUI_DispStringInRect("Æô", &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
		}


		break;
	default:
		BUTTON_Callback(pMsg);
	}
}

/*********************************************************************
*
*       _cbButton3
*
**********************************************************************
*/
static void _cbButton3(WM_MESSAGE * pMsg) //--------------ï¼?ï¼?
{

	GUI_RECT Rect;

	switch (pMsg->MsgId)
	{
	case WM_PAINT:
		WM_GetClientRect(&Rect);

		if (sw_flag23 == 3)
		{

			GUI_SetColor(GUI_RED);
			GUI_FillRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);
			GUI_SetBkColor(GUI_RED);
			GUI_SetColor(GUI_BLACK);
			GUI_SetFont(&GUI_FontHZ16);
			GUI_DispStringInRect("Í£", &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);

		}

		if (sw_flag23 != 3)
		{

			GUI_SetColor(GUI_GRAY);
			GUI_FillRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);
			GUI_SetBkColor(GUI_GRAY);

			GUI_SetColor(GUI_BLACK);
			GUI_SetPenSize(1);
			GUI_DrawRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);

			GUI_SetColor(GUI_BLACK);
			GUI_SetFont(&GUI_FontHZ16);
			GUI_DispStringInRect("Í£", &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
		}

		break;
	default:
		BUTTON_Callback(pMsg);
	}
}

/*********************************************************************
*
*       _cbButton6
*
**********************************************************************
*/
static void _cbButton6(WM_MESSAGE * pMsg) //--------------ï¼?ï¼?
{

	GUI_RECT Rect;

	switch (pMsg->MsgId)
	{
	case WM_PAINT:
		WM_GetClientRect(&Rect);

		if (sw_flag67 == 6)
		{

			GUI_SetColor(GUI_GREEN);
			GUI_FillRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);
			GUI_SetBkColor(GUI_GREEN);
			GUI_SetColor(GUI_BLACK);
			GUI_SetFont(&GUI_FontHZ16);
			GUI_DispStringInRect("Æô", &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);

		}
		if (sw_flag67!=6)
		{

			GUI_SetColor(GUI_LIGHTGRAY);
			GUI_FillRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);
			GUI_SetBkColor(GUI_LIGHTGRAY);

			GUI_SetColor(GUI_BLACK);
			GUI_SetPenSize(1);
			GUI_DrawRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);

			GUI_SetColor(GUI_BLACK);
			GUI_SetFont(&GUI_FontHZ16);
			GUI_DispStringInRect("Æô", &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
		}

		break;
	default:
		BUTTON_Callback(pMsg);
	}
}

/*********************************************************************
*
*       _cbButton7
*
**********************************************************************
*/
static void _cbButton7(WM_MESSAGE * pMsg) //--------------ï¼?ï¼?
{

	GUI_RECT Rect;

	switch (pMsg->MsgId)
	{
	case WM_PAINT:
		WM_GetClientRect(&Rect);

		if (sw_flag67 == 7)
		{

			GUI_SetColor(GUI_RED);
			GUI_FillRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);
			GUI_SetBkColor(GUI_RED);
			GUI_SetColor(GUI_BLACK);
			GUI_SetFont(&GUI_FontHZ16);
			GUI_DispStringInRect("Í£", &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
		}
		if (sw_flag67 != 7)
		{
			GUI_SetColor(GUI_GRAY);
			GUI_FillRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);
			GUI_SetBkColor(GUI_GRAY);

			GUI_SetColor(GUI_BLACK);
			GUI_SetPenSize(1);
			GUI_DrawRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);

			GUI_SetColor(GUI_BLACK);
			GUI_SetFont(&GUI_FontHZ16);
			GUI_DispStringInRect("Í£", &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
		}

		break;
	default:
		BUTTON_Callback(pMsg);
	}
}

/*********************************************************************
*
*       _cbButton10
*
**********************************************************************
*/
static void _cbButton10(WM_MESSAGE * pMsg) //--------------ï¼?ï¼?
{

	GUI_RECT Rect;


	switch (pMsg->MsgId)
	{
	case WM_PAINT:
		WM_GetClientRect(&Rect);

		if (sw_flag1011 == 10)//if (BUTTON_IsPressed(hWin))
		{
			GUI_SetColor(GUI_GREEN);
			GUI_FillRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);
			GUI_SetBkColor(GUI_GREEN);
			GUI_SetColor(GUI_BLACK);
			GUI_SetFont(&GUI_FontHZ16);
			GUI_DispStringInRect("Æô", &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);

		}
		if (sw_flag1011 != 10)
		{

			GUI_SetColor(GUI_LIGHTGRAY);
			GUI_FillRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);
			GUI_SetBkColor(GUI_LIGHTGRAY);

			GUI_SetColor(GUI_BLACK);
			GUI_SetPenSize(1);
			GUI_DrawRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);

			GUI_SetColor(GUI_BLACK);
			GUI_SetFont(&GUI_FontHZ16);
			GUI_DispStringInRect("Æô", &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
		}


		break;
	default:
		BUTTON_Callback(pMsg);
	}
}

/*********************************************************************
*
*       _cbButton11
*
**********************************************************************
*/
static void _cbButton11(WM_MESSAGE * pMsg) //--------------ï¼?ï¼?
{

	GUI_RECT Rect;

	switch (pMsg->MsgId)
	{
	case WM_PAINT:
		WM_GetClientRect(&Rect);

		if (sw_flag1011 == 11)
		{

			GUI_SetColor(GUI_RED);
			GUI_FillRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);
			GUI_SetBkColor(GUI_RED);
			GUI_SetColor(GUI_BLACK);
			GUI_SetFont(&GUI_FontHZ16);
			GUI_DispStringInRect("Í£", &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);

		}

		if (sw_flag1011 != 11)
		{

			GUI_SetColor(GUI_GRAY);
			GUI_FillRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);
			GUI_SetBkColor(GUI_GRAY);

			GUI_SetColor(GUI_BLACK);
			GUI_SetPenSize(1);
			GUI_DrawRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);

			GUI_SetColor(GUI_BLACK);
			GUI_SetFont(&GUI_FontHZ16);
			GUI_DispStringInRect("Í£", &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
		}

		break;
	default:
		BUTTON_Callback(pMsg);
	}
}

/*********************************************************************
*
*       _cbButton14
*
**********************************************************************
*/
static void _cbButton14(WM_MESSAGE * pMsg) //--------------ï¼?ï¼?
{

	GUI_RECT Rect;

	switch (pMsg->MsgId)
	{
	case WM_PAINT:
		WM_GetClientRect(&Rect);

		if (sw_flag1415 == 14)
		{

			GUI_SetColor(GUI_GREEN);
			GUI_FillRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);
			GUI_SetBkColor(GUI_GREEN);
			GUI_SetColor(GUI_BLACK);
			GUI_SetFont(&GUI_FontHZ16);
			GUI_DispStringInRect("Æô", &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);

		}
		if (sw_flag1415 != 14)
		{

			GUI_SetColor(GUI_LIGHTGRAY);
			GUI_FillRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);
			GUI_SetBkColor(GUI_LIGHTGRAY);

			GUI_SetColor(GUI_BLACK);
			GUI_SetPenSize(1);
			GUI_DrawRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);

			GUI_SetColor(GUI_BLACK);
			GUI_SetFont(&GUI_FontHZ16);
			GUI_DispStringInRect("Æô", &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
		}

		break;
	default:
		BUTTON_Callback(pMsg);
	}
}

/*********************************************************************
*
*       _cbButton15
*
**********************************************************************
*/
static void _cbButton15(WM_MESSAGE * pMsg) //--------------ï¼?ï¼?
{

	GUI_RECT Rect;

	switch (pMsg->MsgId)
	{
	case WM_PAINT:
		WM_GetClientRect(&Rect);

		if (sw_flag1415 == 15)
		{

			GUI_SetColor(GUI_RED);
			GUI_FillRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);
			GUI_SetBkColor(GUI_RED);
			GUI_SetColor(GUI_BLACK);
			GUI_SetFont(&GUI_FontHZ16);
			GUI_DispStringInRect("Í£", &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
		}
		if (sw_flag1415 != 15)
		{
			GUI_SetColor(GUI_GRAY);
			GUI_FillRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);
			GUI_SetBkColor(GUI_GRAY);

			GUI_SetColor(GUI_BLACK);
			GUI_SetPenSize(1);
			GUI_DrawRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);

			GUI_SetColor(GUI_BLACK);
			GUI_SetFont(&GUI_FontHZ16);
			GUI_DispStringInRect("Í£", &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
		}

		break;
	default:
		BUTTON_Callback(pMsg);
	}
}

/*********************************************************************
*
*       _cbButton18
*
**********************************************************************
*/
static void _cbButton18(WM_MESSAGE * pMsg) //--------------ï¼?ï¼?
{

	GUI_RECT Rect;

	switch (pMsg->MsgId)
	{
	case WM_PAINT:
		WM_GetClientRect(&Rect);

		if (sw_flag1819 == 18)
		{

			GUI_SetColor(GUI_GREEN);
			GUI_FillRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);
			GUI_SetBkColor(GUI_GREEN);
			GUI_SetColor(GUI_BLACK);
			GUI_SetFont(&GUI_FontHZ16);
			GUI_DispStringInRect("Æô", &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);

		}
		if (sw_flag1819 != 18)
		{

			GUI_SetColor(GUI_LIGHTGRAY);
			GUI_FillRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);
			GUI_SetBkColor(GUI_LIGHTGRAY);

			GUI_SetColor(GUI_BLACK);
			GUI_SetPenSize(1);
			GUI_DrawRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);

			GUI_SetColor(GUI_BLACK);
			GUI_SetFont(&GUI_FontHZ16);
			GUI_DispStringInRect("Æô", &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
		}

		break;
	default:
		BUTTON_Callback(pMsg);
	}
}

/*********************************************************************
*
*       _cbButton19
*
**********************************************************************
*/
static void _cbButton19(WM_MESSAGE * pMsg) //--------------ï¼?ï¼?
{

	GUI_RECT Rect;

	switch (pMsg->MsgId)
	{
	case WM_PAINT:
		WM_GetClientRect(&Rect);

		if (sw_flag1819 == 19)
		{

			GUI_SetColor(GUI_RED);
			GUI_FillRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);
			GUI_SetBkColor(GUI_RED);
			GUI_SetColor(GUI_BLACK);
			GUI_SetFont(&GUI_FontHZ16);
			GUI_DispStringInRect("Í£", &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
		}
		if (sw_flag1819 != 19)
		{
			GUI_SetColor(GUI_GRAY);
			GUI_FillRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);
			GUI_SetBkColor(GUI_GRAY);

			GUI_SetColor(GUI_BLACK);
			GUI_SetPenSize(1);
			GUI_DrawRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);

			GUI_SetColor(GUI_BLACK);
			GUI_SetFont(&GUI_FontHZ16);
			GUI_DispStringInRect("Í£", &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
		}

		break;
	default:
		BUTTON_Callback(pMsg);
	}
}

/*********************************************************************
*
*       _cbButton22
*
**********************************************************************
*/
static void _cbButton22(WM_MESSAGE * pMsg) //--------------ï¼?ï¼?
{

	GUI_RECT Rect;

	switch (pMsg->MsgId)
	{
	case WM_PAINT:
		WM_GetClientRect(&Rect);

		if (sw_flag2223 == 22)
		{

			GUI_SetColor(GUI_GREEN);
			GUI_FillRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);
			GUI_SetBkColor(GUI_GREEN);
			GUI_SetColor(GUI_BLACK);
			GUI_SetFont(&GUI_FontHZ16);
			GUI_DispStringInRect("Æô", &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);

		}
		if (sw_flag2223 != 22)
		{

			GUI_SetColor(GUI_LIGHTGRAY);
			GUI_FillRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);
			GUI_SetBkColor(GUI_LIGHTGRAY);

			GUI_SetColor(GUI_BLACK);
			GUI_SetPenSize(1);
			GUI_DrawRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);

			GUI_SetColor(GUI_BLACK);
			GUI_SetFont(&GUI_FontHZ16);
			GUI_DispStringInRect("Æô", &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
		}

		break;
	default:
		BUTTON_Callback(pMsg);
	}
}

/*********************************************************************
*
*       _cbButton23
*
**********************************************************************
*/
static void _cbButton23(WM_MESSAGE * pMsg) //--------------ï¼?ï¼?
{

	GUI_RECT Rect;

	switch (pMsg->MsgId)
	{
	case WM_PAINT:
		WM_GetClientRect(&Rect);

		if (sw_flag2223 == 23)
		{

			GUI_SetColor(GUI_RED);
			GUI_FillRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);
			GUI_SetBkColor(GUI_RED);
			GUI_SetColor(GUI_BLACK);
			GUI_SetFont(&GUI_FontHZ16);
			GUI_DispStringInRect("Í£", &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
		}
		if (sw_flag2223 != 23)
		{
			GUI_SetColor(GUI_GRAY);
			GUI_FillRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);
			GUI_SetBkColor(GUI_GRAY);

			GUI_SetColor(GUI_BLACK);
			GUI_SetPenSize(1);
			GUI_DrawRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);

			GUI_SetColor(GUI_BLACK);
			GUI_SetFont(&GUI_FontHZ16);
			GUI_DispStringInRect("Í£", &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
		}

		break;
	default:
		BUTTON_Callback(pMsg);
	}
}

/*********************************************************************
*
*       _cbButton26
*
**********************************************************************
*/
static void _cbButton26(WM_MESSAGE * pMsg) //--------------ï¼?ï¼?
{

	GUI_RECT Rect;

	switch (pMsg->MsgId)
	{
	case WM_PAINT:
		WM_GetClientRect(&Rect);

		if (sw_flag2627 == 26)
		{

			GUI_SetColor(GUI_GREEN);
			GUI_FillRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);
			GUI_SetBkColor(GUI_GREEN);
			GUI_SetColor(GUI_BLACK);
			GUI_SetFont(&GUI_FontHZ16);
			GUI_DispStringInRect("Æô", &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);

		}
		if (sw_flag2627 != 26)
		{

			GUI_SetColor(GUI_LIGHTGRAY);
			GUI_FillRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);
			GUI_SetBkColor(GUI_LIGHTGRAY);

			GUI_SetColor(GUI_BLACK);
			GUI_SetPenSize(1);
			GUI_DrawRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);

			GUI_SetColor(GUI_BLACK);
			GUI_SetFont(&GUI_FontHZ16);
			GUI_DispStringInRect("Æô", &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
		}

		break;
	default:
		BUTTON_Callback(pMsg);
	}
}

/*********************************************************************
*
*       _cbButton27
*
**********************************************************************
*/

static void _cbButton27(WM_MESSAGE * pMsg) //--------------ï¼?ï¼?
{

	GUI_RECT Rect;

	switch (pMsg->MsgId)
	{
	case WM_PAINT:
		WM_GetClientRect(&Rect);

		if (sw_flag2627 == 27)
		{

			GUI_SetColor(GUI_RED);
			GUI_FillRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);
			GUI_SetBkColor(GUI_RED);
			GUI_SetColor(GUI_BLACK);
			GUI_SetFont(&GUI_FontHZ16);
			GUI_DispStringInRect("Í£", &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
		}
		if (sw_flag2627 != 27)
		{
			GUI_SetColor(GUI_GRAY);
			GUI_FillRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);
			GUI_SetBkColor(GUI_GRAY);

			GUI_SetColor(GUI_BLACK);
			GUI_SetPenSize(1);
			GUI_DrawRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);

			GUI_SetColor(GUI_BLACK);
			GUI_SetFont(&GUI_FontHZ16);
			GUI_DispStringInRect("Í£", &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
		}

		break;
	default:
		BUTTON_Callback(pMsg);
	}
}
/*********************************************************************
*
*       _cbButton29
*
**********************************************************************
*/
static void _cbButton29(WM_MESSAGE * pMsg) //--------------ï¼?ï¼?
{

	GUI_RECT Rect;

	switch (pMsg->MsgId)
	{
	case WM_PAINT:
		WM_GetClientRect(&Rect);

		if (sw_flag2930 == 29)
		{

			GUI_SetColor(GUI_GREEN);
			GUI_FillRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);
			GUI_SetBkColor(GUI_GREEN);
			GUI_SetColor(GUI_BLACK);
			GUI_SetFont(&GUI_FontHZ16);
			GUI_DispStringInRect("ÉÏÉý", &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
		}
		if (sw_flag2930!= 29)
		{
			GUI_SetColor(GUI_LIGHTGRAY);
			GUI_FillRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);
			GUI_SetBkColor(GUI_LIGHTGRAY);

			GUI_SetColor(GUI_BLACK);
			GUI_SetPenSize(1);
			GUI_DrawRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);

			GUI_SetColor(GUI_BLACK);
			GUI_SetFont(&GUI_FontHZ16);
			GUI_DispStringInRect("ÉÏÉý", &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
		}

		break;
	default:
		BUTTON_Callback(pMsg);
	}
}

/*********************************************************************
*
*       _cbButton30
*
**********************************************************************
*/
static void _cbButton30(WM_MESSAGE * pMsg) //--------------ï¼?ï¼?
{

	GUI_RECT Rect;

	switch (pMsg->MsgId)
	{
	case WM_PAINT:
		WM_GetClientRect(&Rect);

		if (sw_flag2930 == 30)
		{

			GUI_SetColor(GUI_DARKBLUE);
			GUI_FillRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);
			GUI_SetBkColor(GUI_DARKBLUE);
			GUI_SetColor(GUI_WHITE);
			GUI_SetFont(&GUI_FontHZ16);
			GUI_DispStringInRect("ÏÂ½µ", &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
		}
		if (sw_flag2930 != 30)
		{
			GUI_SetColor(GUI_LIGHTGRAY);
			GUI_FillRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);
			GUI_SetBkColor(GUI_LIGHTGRAY);

			GUI_SetColor(GUI_BLACK);
			GUI_SetPenSize(1);
			GUI_DrawRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);

			GUI_SetColor(GUI_BLACK);
			GUI_SetFont(&GUI_FontHZ16);
			GUI_DispStringInRect("ÏÂ½µ", &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
		}

		break;
	default:
		BUTTON_Callback(pMsg);
	}
}

/*********************************************************************
*
*       _cbButton31
*
**********************************************************************
*/
static void _cbButton31(WM_MESSAGE * pMsg) //--------------ï¼?ï¼?
{

	GUI_RECT Rect;

	switch (pMsg->MsgId)
	{
	case WM_PAINT:
		WM_GetClientRect(&Rect);

		if (sw_flag3132 == 31)
		{

			GUI_SetColor(GUI_GREEN);
			GUI_FillRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);
			GUI_SetBkColor(GUI_GREEN);
			GUI_SetColor(GUI_BLACK);
			GUI_SetFont(&GUI_FontHZ16);
			GUI_DispStringInRect("ÉÏÉý", &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
		}
		if (sw_flag3132 != 31)
		{
			GUI_SetColor(GUI_LIGHTGRAY);
			GUI_FillRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);
			GUI_SetBkColor(GUI_LIGHTGRAY);

			GUI_SetColor(GUI_BLACK);
			GUI_SetPenSize(1);
			GUI_DrawRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);

			GUI_SetColor(GUI_BLACK);
			GUI_SetFont(&GUI_FontHZ16);
			GUI_DispStringInRect("ÉÏÉý", &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
		}

		break;
	default:
		BUTTON_Callback(pMsg);
	}
}

/*********************************************************************
*
*       _cbButton32
*
**********************************************************************
*/
static void _cbButton32(WM_MESSAGE * pMsg) //--------------ï¼?ï¼?
{

	GUI_RECT Rect;

	switch (pMsg->MsgId)
	{
	case WM_PAINT:
		WM_GetClientRect(&Rect);

		if (sw_flag3132 == 32)
		{

			GUI_SetColor(GUI_DARKBLUE);
			GUI_FillRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);
			GUI_SetBkColor(GUI_DARKBLUE);
			GUI_SetColor(GUI_WHITE);
			GUI_SetFont(&GUI_FontHZ16);
			GUI_DispStringInRect("ÏÂ½µ", &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
		}
		if (sw_flag3132 != 32)
		{
			GUI_SetColor(GUI_LIGHTGRAY);
			GUI_FillRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);
			GUI_SetBkColor(GUI_LIGHTGRAY);

			GUI_SetColor(GUI_BLACK);
			GUI_SetPenSize(1);
			GUI_DrawRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);

			GUI_SetColor(GUI_BLACK);
			GUI_SetFont(&GUI_FontHZ16);
			GUI_DispStringInRect("ÏÂ½µ", &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
		}

		break;
	default:
		BUTTON_Callback(pMsg);
	}
}

// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void MotorcontrolWindow_cbDialog(WM_MESSAGE * pMsg) {
	WM_HWIN hItem;
	WM_HWIN	putinDLG;
	int     NCode;
	int     Id;

	int i;
	// USER Æô (Optionally insert additional variables)


	// USER END

	switch (pMsg->MsgId) {
	case WM_INIT_DIALOG:
		//
		// Initialization of 'ar_motor_control'
		//
		/************************1å?************************************/

		hItem = pMsg->hWin;


		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
		TEXT_SetFont(hItem, &GUI_FontHZ24);
		TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
		//
		// Initialization of 'Mspeed_1'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
		TEXT_SetFont(hItem, &GUI_FontHZ16);
		TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
		//
		// Initialization of 'Dspeed_1'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
		TEXT_SetFont(hItem, &GUI_FontHZ16);
		TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
		//
		// Initialization of 'speedup_1'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
		BUTTON_SetFont(hItem, &GUI_FontHZ16);
		//
		// Initialization of 'speeddown_1'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
		BUTTON_SetFont(hItem, &GUI_FontHZ16);
		//
		// Initialization of 'fanzhuan_1'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_0);
		CHECKBOX_SetText(hItem, "·´×ª");
		CHECKBOX_SetFont(hItem, &GUI_FontHZ16);
		//
		// Initialization of 'zhengzhuan_1'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_1);
		CHECKBOX_SetText(hItem, "Õý×ª");
		CHECKBOX_SetFont(hItem, &GUI_FontHZ16);
		CHECKBOX_SetState(hItem , 1);
		WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_1));

		//
		// Initialization of 'Æô_1'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
		BUTTON_SetFont(hItem, &GUI_FontHZ16);
		WM_SetCallback(hItem, _cbButton2);
		//
		// Initialization of 'Í£_1'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);
		BUTTON_SetFont(hItem, &GUI_FontHZ16);
		//WM_SetHasTrans(hItem);
		WM_SetCallback(hItem, _cbButton3);
		/************************1å?************************************/

		/************************2å?************************************/
		//
		// Initialization of 'Ä¿±êËÙ¶È'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
		TEXT_SetFont(hItem, &GUI_FontHZ16);
		TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
		//
		// Initialization of 'µ±Ç°ËÙ¶È'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);
		TEXT_SetFont(hItem, &GUI_FontHZ16);
		TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
		//
		// Initialization of 'ËÙ¶È+'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_4);
		BUTTON_SetFont(hItem, &GUI_FontHZ16);
		//
		// Initialization of 'ËÙ¶È-'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_5);
		BUTTON_SetFont(hItem, &GUI_FontHZ16);
		//
		// Initialization of 'Æô'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_6);
		BUTTON_SetFont(hItem, &GUI_FontHZ16);
		WM_SetCallback(hItem, _cbButton6);
		//
		// Initialization of 'Í£'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_7);
		BUTTON_SetFont(hItem, &GUI_FontHZ16);
		WM_SetCallback(hItem, _cbButton7);
		//
		// Initialization of '·´×ª'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_2);
		CHECKBOX_SetText(hItem, "·´×ª");
		CHECKBOX_SetFont(hItem, &GUI_FontHZ16);
		//
		// Initialization of 'Õý×ª'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_3);
		CHECKBOX_SetText(hItem, "Õý×ª");
		CHECKBOX_SetFont(hItem, &GUI_FontHZ16);
		CHECKBOX_SetState(hItem, 1);
		WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_3));
		/************************2å?************************************/

		/************************3å?************************************/
		//
		// Initialization of 'Mspeed_3'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_5);
		TEXT_SetFont(hItem, &GUI_FontHZ16);
		TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
		//
		// Initialization of 'Dspeed_3'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_6);
		TEXT_SetFont(hItem, &GUI_FontHZ16);
		TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
		//
		// Initialization of 'speedup_3'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_8);
		BUTTON_SetFont(hItem, &GUI_FontHZ16);
		//
		// Initialization of 'speeddown_3'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_9);
		BUTTON_SetFont(hItem, &GUI_FontHZ16);
		//
		// Initialization of 'Æô_3'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_10);
		BUTTON_SetFont(hItem, &GUI_FontHZ16);
		WM_SetCallback(hItem, _cbButton10);
		//
		// Initialization of 'Í£_3'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_11);
		BUTTON_SetFont(hItem, &GUI_FontHZ16);
		WM_SetCallback(hItem, _cbButton11);
		//
		// Initialization of 'fanzhuan_3'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_4);
		CHECKBOX_SetText(hItem, "·´×ª");
		CHECKBOX_SetFont(hItem, &GUI_FontHZ16);
		//
		// Initialization of 'zhengzhuan_3'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_5);
		CHECKBOX_SetText(hItem, "Õý×ª");
		CHECKBOX_SetFont(hItem, &GUI_FontHZ16);
		CHECKBOX_SetState(hItem, 1);
		WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_5));
		/************************3å?************************************/

		/************************4å?************************************/
		//
		// Initialization of 'Mspeed_4'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_7);
		TEXT_SetFont(hItem, &GUI_FontHZ16);
		TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
		//
		// Initialization of 'Dspeed_4'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_8);
		TEXT_SetFont(hItem, &GUI_FontHZ16);
		TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
		//
		// Initialization of 'speedup_4'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_12);
		BUTTON_SetFont(hItem, &GUI_FontHZ16);
		//
		// Initialization of 'speeddown_4'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_13);
		BUTTON_SetFont(hItem, &GUI_FontHZ16);
		//
		// Initialization of 'Æô_4'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_14);
		BUTTON_SetFont(hItem, &GUI_FontHZ16);
		WM_SetCallback(hItem, _cbButton14);
		//
		// Initialization of 'Í£_4'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_15);
		BUTTON_SetFont(hItem, &GUI_FontHZ16);
		WM_SetCallback(hItem, _cbButton15);
		//
		// Initialization of 'fanzhuan_4'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_6);
		CHECKBOX_SetText(hItem, "·´×ª");
		CHECKBOX_SetFont(hItem, &GUI_FontHZ16);
		//
		// Initialization of 'zhengzhuan_4'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_7);
		CHECKBOX_SetText(hItem, "Õý×ª");
		CHECKBOX_SetFont(hItem, &GUI_FontHZ16);
		CHECKBOX_SetState(hItem, 1);
		WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_7));
		/************************4å?************************************/

		/************************5å?************************************/
		//
		// Initialization of 'Mspeed_5'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_9);
		TEXT_SetFont(hItem, &GUI_FontHZ16);
		TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
		//
		// Initialization of 'Dspeed_5'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_10);
		TEXT_SetFont(hItem, &GUI_FontHZ16);
		TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
		//
		// Initialization of 'speedup_5'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_16);
		BUTTON_SetFont(hItem, &GUI_FontHZ16);
		//
		// Initialization of 'speeddown_5'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_17);
		BUTTON_SetFont(hItem, &GUI_FontHZ16);
		//
		// Initialization of 'Æô_5'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_18);
		BUTTON_SetFont(hItem, &GUI_FontHZ16);
		WM_SetCallback(hItem, _cbButton18);
		//
		// Initialization of 'Í£_5'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_19);
		BUTTON_SetFont(hItem, &GUI_FontHZ16);
		WM_SetCallback(hItem, _cbButton19);
		//
		// Initialization of 'fanzhuan_5'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_8);
		CHECKBOX_SetText(hItem, "·´×ª");
		CHECKBOX_SetFont(hItem, &GUI_FontHZ16);
		//
		// Initialization of 'zhengzhuan_5'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_9);
		CHECKBOX_SetText(hItem, "Õý×ª");
		CHECKBOX_SetFont(hItem, &GUI_FontHZ16);
		CHECKBOX_SetState(hItem, 1);
		WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_9));
		/************************5å?************************************/

		/************************6å?************************************/
		//
		// Initialization of 'Mspeed_6'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_11);
		TEXT_SetFont(hItem, &GUI_FontHZ16);
		TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
		//
		// Initialization of 'Dspeed_6'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_12);
		TEXT_SetFont(hItem, &GUI_FontHZ16);
		TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
		//
		// Initialization of 'speedup_6'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_20);
		BUTTON_SetFont(hItem, &GUI_FontHZ16);
		//
		// Initialization of 'speeddown_6'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_21);
		BUTTON_SetFont(hItem, &GUI_FontHZ16);
		//
		// Initialization of 'Æô_6'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_22);
		BUTTON_SetFont(hItem, &GUI_FontHZ16);
		WM_SetCallback(hItem, _cbButton22);
		//
		// Initialization of 'Í£_6'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_23);
		BUTTON_SetFont(hItem, &GUI_FontHZ16);
		WM_SetCallback(hItem, _cbButton23);
		//
		// Initialization of 'fanzhuan_6'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_10);
		CHECKBOX_SetText(hItem, "·´×ª");
		CHECKBOX_SetFont(hItem, &GUI_FontHZ16);
		//
		// Initialization of 'zhengzhuan_6'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_11);
		CHECKBOX_SetText(hItem, "Õý×ª");
		CHECKBOX_SetFont(hItem, &GUI_FontHZ16);
		CHECKBOX_SetState(hItem, 1);
		WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_11));
		/************************6å?************************************/

		/************************7å?************************************/
		//
		// Initialization of 'Mspeed_7'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_13);
		TEXT_SetFont(hItem, &GUI_FontHZ16);
		TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
		//
		// Initialization of 'Dspeed_7'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_14);
		TEXT_SetFont(hItem, &GUI_FontHZ16);
		TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
		//
		// Initialization of 'speedup_7'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_24);
		BUTTON_SetFont(hItem, &GUI_FontHZ16);
		//
		// Initialization of 'speeddown_7'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_25);
		BUTTON_SetFont(hItem, &GUI_FontHZ16);
		//
		// Initialization of 'Æô_7'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_26);
		BUTTON_SetFont(hItem, &GUI_FontHZ16);
		WM_SetCallback(hItem, _cbButton26);
		//
		// Initialization of 'Í£_7'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_27);
		BUTTON_SetFont(hItem, &GUI_FontHZ16);
		WM_SetCallback(hItem, _cbButton27);
		//
		// Initialization of 'fanzhuan_7'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_12);
		CHECKBOX_SetText(hItem, "·´×ª");
		CHECKBOX_SetFont(hItem, &GUI_FontHZ16);
		//
		// Initialization of 'zhengzhuan_7'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_13);
		CHECKBOX_SetText(hItem, "Õý×ª");
		CHECKBOX_SetFont(hItem, &GUI_FontHZ16);
		CHECKBOX_SetState(hItem, 1);
		WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_13));
		/************************7å?************************************/
		
		// USER Æô (Optionally insert additional code for further widget initialization)
		//add
		/*é€Ÿåº¦æ˜¾ç¤ºEDITæŽ§ä»¶*/
		//1å?
		hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_1);
		EDIT_SetText(hItem, "0");
		EDIT_SetFont(hItem, &GUI_FontHZ16);
		EDIT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
		EDIT_SetDecMode(hItem, 30, 0,100, 0, 0);

		hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_2);
		EDIT_SetText(hItem, "0");
		EDIT_SetFont(hItem, &GUI_FontHZ16);
		EDIT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);

		//2å?
		hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_3);
		EDIT_SetText(hItem, "0");
		EDIT_SetFont(hItem, &GUI_FontHZ16);
		EDIT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
		EDIT_SetDecMode(hItem, 30, 0, 100, 0, 0);

		hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_4);
		EDIT_SetText(hItem, "0");
		EDIT_SetFont(hItem, &GUI_FontHZ16);
		EDIT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);

		//3å?
		hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_5);
		EDIT_SetText(hItem, "0");
		EDIT_SetFont(hItem, &GUI_FontHZ16);
		EDIT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
		EDIT_SetDecMode(hItem, 30, 0, 100, 0, 0);

		hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_6);
		EDIT_SetText(hItem, "0");
		EDIT_SetFont(hItem, &GUI_FontHZ16);
		EDIT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);

		//4å?
		hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_7);
		EDIT_SetText(hItem, "0");
		EDIT_SetFont(hItem, &GUI_FontHZ16);
		EDIT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
		EDIT_SetDecMode(hItem, 30, 0, 100, 0, 0);

		hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_8);
		EDIT_SetText(hItem, "0");
		EDIT_SetFont(hItem, &GUI_FontHZ16);
		EDIT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
		//5å?
		hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_9);
		EDIT_SetText(hItem, "0");
		EDIT_SetFont(hItem, &GUI_FontHZ16);
		EDIT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
		EDIT_SetDecMode(hItem, 30, 0, 100, 0, 0);

		hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_10);
		EDIT_SetText(hItem, "0");
		EDIT_SetFont(hItem, &GUI_FontHZ16);
		EDIT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
		//6å?
		hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_11);
		EDIT_SetText(hItem, "0");
		EDIT_SetFont(hItem, &GUI_FontHZ16);
		EDIT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
		EDIT_SetDecMode(hItem, 30, 0, 100, 0, 0);

		hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_12);
		EDIT_SetText(hItem, "0");
		EDIT_SetFont(hItem, &GUI_FontHZ16);
		EDIT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
		//7å?
		hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_13);
		EDIT_SetText(hItem, "0");
		EDIT_SetFont(hItem, &GUI_FontHZ16);
		EDIT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
		EDIT_SetDecMode(hItem, 30, 0, 100, 0, 0);

		hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_14);
		EDIT_SetText(hItem, "0");
		EDIT_SetFont(hItem, &GUI_FontHZ16);
		EDIT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
       /**è¿”å›žä¸»èœå•æŒ‰é’?**/
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_28);
		BUTTON_SetFont(hItem, &GUI_FontHZ24);
		/***ç”µæœºå·æ˜¾ç¤?**/
		//1å?
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_15);
		TEXT_SetFont(hItem, &GUI_FontHZ16);
		TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
		//2å?
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_16);
		TEXT_SetFont(hItem, &GUI_FontHZ16);
		TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
		//3å?
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_17);
		TEXT_SetFont(hItem, &GUI_FontHZ16);
		TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
		//4å?
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_18);
		TEXT_SetFont(hItem, &GUI_FontHZ16);
		TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
		//5å?
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_19);
		TEXT_SetFont(hItem, &GUI_FontHZ16);
		TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
		//6å?
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_20);
		TEXT_SetFont(hItem, &GUI_FontHZ16);
		TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
		//7å?
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_21);
		TEXT_SetFont(hItem, &GUI_FontHZ16);
		TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
		/*****æ°”ç¼¸******/
		//1
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_31);
		TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		TEXT_SetFont(hItem, &GUI_FontHZ16);
		
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_29);
		BUTTON_SetFont(hItem, &GUI_FontHZ16);
		WM_SetCallback(hItem, _cbButton29);

		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_30);
		BUTTON_SetFont(hItem, &GUI_FontHZ16);
		WM_SetCallback(hItem, _cbButton30);

		//2
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_32);
		TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		TEXT_SetFont(hItem, &GUI_FontHZ16);

		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_31);
		BUTTON_SetFont(hItem, &GUI_FontHZ16);
		WM_SetCallback(hItem, _cbButton31);

		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_32);
		BUTTON_SetFont(hItem, &GUI_FontHZ16);
		WM_SetCallback(hItem, _cbButton32);


		// USER END
		break;
	case WM_NOTIFY_PARENT:
		Id = WM_GetId(pMsg->hWinSrc);
		NCode = pMsg->Data.v;
		switch (Id) {
			/************BUTTON**************/
		case ID_BUTTON_2: // Notifications sent by 'Æô_1'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				WM_InvalidateWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3));
				sw_flag23 = 2;
				break;
			case WM_NOTIFICATION_RELEASED:
				break;
			}
			break;
		case ID_BUTTON_3: // Notifications sent by 'Í£_1'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				WM_InvalidateWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2));
				sw_flag23 = 3;
				break;
			case WM_NOTIFICATION_RELEASED:
				break;
			}
			break;
		case ID_BUTTON_6: // Notifications sent by 'Æô_1'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				WM_InvalidateWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_7));
				sw_flag67 = 6;
				break;
			case WM_NOTIFICATION_RELEASED:
				break;
			}
			break;
		case ID_BUTTON_7: // Notifications sent by 'Í£_1'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				WM_InvalidateWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_6));
				sw_flag67 = 7;
				break;
			case WM_NOTIFICATION_RELEASED:
				break;
			}
			break;
		case ID_BUTTON_10: // Notifications sent by 'Í£_1'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				WM_InvalidateWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_11));
				sw_flag1011 = 10;
				break;
			case WM_NOTIFICATION_RELEASED:
				break;
			}
			break;

		case ID_BUTTON_11: // Notifications sent by 'Í£_1'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				WM_InvalidateWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_10));
				sw_flag1011 = 11;
				break;
			case WM_NOTIFICATION_RELEASED:
				break;
			}
			break;
		case ID_BUTTON_14: // Notifications sent by 'Í£_1'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				WM_InvalidateWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_15));
				sw_flag1415 = 14;
				break;
			case WM_NOTIFICATION_RELEASED:
				break;
			}
			break;

		case ID_BUTTON_15: // Notifications sent by 'Í£_1'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				WM_InvalidateWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_14));
				sw_flag1415 = 15;
				break;
			case WM_NOTIFICATION_RELEASED:
				break;
			}
			break;
		case ID_BUTTON_18: // Notifications sent by 'Í£_1'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				WM_InvalidateWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_19));
				sw_flag1819 = 18;
				break;
			case WM_NOTIFICATION_RELEASED:
				break;
			}
			break;

		case ID_BUTTON_19: // Notifications sent by 'Í£_1'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				WM_InvalidateWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_18));
				sw_flag1819 = 19;
				break;
			case WM_NOTIFICATION_RELEASED:
				break;
			}
			break;
		case ID_BUTTON_22: // Notifications sent by 'Í£_1'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				WM_InvalidateWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_23));
				sw_flag2223 = 22;
				break;
			case WM_NOTIFICATION_RELEASED:
				break;
			}
			break;

		case ID_BUTTON_23: // Notifications sent by 'Í£_1'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				WM_InvalidateWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_22));
				sw_flag2223 = 23;
				break;
			case WM_NOTIFICATION_RELEASED:
				break;
			}
			break;
		case ID_BUTTON_26: // Notifications sent by 'Í£_1'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				WM_InvalidateWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_27));
				sw_flag2627 = 26;
				break;
			case WM_NOTIFICATION_RELEASED:
				break;
			}
			break;

		case ID_BUTTON_27: // Notifications sent by 'Í£_1'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				WM_InvalidateWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_26));
				sw_flag2627 = 27;
				break;
			case WM_NOTIFICATION_RELEASED:
				break;
			}
			break;

		case ID_BUTTON_28: // Notifications sent by 'return'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				sw_flag23 = 3;
				sw_flag67 = 7;
				sw_flag1011 = 11;
				sw_flag1415 = 15;
				sw_flag1819 = 19;
				sw_flag2223 = 23;
				sw_flag2627 = 27;
				sw_flag2930 = 30;
				sw_flag3132 = 32;
				break;
			case WM_NOTIFICATION_RELEASED:
				GUI_EndDialog(pMsg->hWin, 0);
				Createar_BKWindow();
				break;
			}
			break;

		case ID_BUTTON_29: // Notifications sent by 'Í£_1'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				WM_InvalidateWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_30));
				sw_flag2930 = 29;
				break;
			case WM_NOTIFICATION_RELEASED:
				break;
			}
			break;
		case ID_BUTTON_30: // Notifications sent by 'Í£_1'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				WM_InvalidateWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_29));
				sw_flag2930 = 30;
				break;
			case WM_NOTIFICATION_RELEASED:
				break;
			}
			break;


		case ID_BUTTON_31: // Notifications sent by 'Í£_1'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				WM_InvalidateWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_32));
				sw_flag3132 = 31;
				break;
			case WM_NOTIFICATION_RELEASED:
				break;
			}
			break;
		case ID_BUTTON_32: // Notifications sent by 'Í£_1'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				WM_InvalidateWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_31));
				sw_flag3132 = 32;
				break;
			case WM_NOTIFICATION_RELEASED:
				break;
			}
			break;

			/**åŠ å‡é€?*/
			//1
		case ID_BUTTON_0: // Notifications sent by 'speedup_1'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
			hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_1);
			WM_SetFocus(hItem);
			EDIT_SetCursorAtChar(hItem, 3);
			GUI_SendKeyMsg(_ar_Key[0], 1);
				break;
			case WM_NOTIFICATION_RELEASED:
				break;
			}
			break;
		case ID_BUTTON_1: // Notifications sent by 'speeddown_1'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
			hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_1);
			WM_SetFocus(hItem);
			EDIT_SetCursorAtChar(hItem, 3);
			GUI_SendKeyMsg(_ar_Key[1], 1);
				break;
			case WM_NOTIFICATION_RELEASED:
				break;
			}
			break;
			//2
		case ID_BUTTON_4: // Notifications sent by 'speedup_1'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_3);
				WM_SetFocus(hItem);
				EDIT_SetCursorAtChar(hItem, 3);
				GUI_SendKeyMsg(_ar_Key[0], 1);
				break;
			case WM_NOTIFICATION_RELEASED:
				break;
			}
			break;
		case ID_BUTTON_5: // Notifications sent by 'speeddown_1'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_3);
				WM_SetFocus(hItem);
				EDIT_SetCursorAtChar(hItem, 3);
				GUI_SendKeyMsg(_ar_Key[1], 1);
				break;
			case WM_NOTIFICATION_RELEASED:
				break;
			}
			break;
			//3
		case ID_BUTTON_8: // Notifications sent by 'speedup_1'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_5);
				WM_SetFocus(hItem);
				EDIT_SetCursorAtChar(hItem, 3);
				GUI_SendKeyMsg(_ar_Key[0], 1);
				break;
			case WM_NOTIFICATION_RELEASED:
				break;
			}
			break;
		case ID_BUTTON_9: // Notifications sent by 'speeddown_1'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_5);
				WM_SetFocus(hItem);
				EDIT_SetCursorAtChar(hItem, 3);
				GUI_SendKeyMsg(_ar_Key[1], 1);
				break;
			case WM_NOTIFICATION_RELEASED:
				break;
			}
			break;
			//4
		case ID_BUTTON_12: // Notifications sent by 'speedup_1'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_7);
				WM_SetFocus(hItem);
				EDIT_SetCursorAtChar(hItem, 3);
				GUI_SendKeyMsg(_ar_Key[0], 1);
				break;
			case WM_NOTIFICATION_RELEASED:
				break;
			}
			break;
		case ID_BUTTON_13: // Notifications sent by 'speeddown_1'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_7);
				WM_SetFocus(hItem);
				EDIT_SetCursorAtChar(hItem, 3);
				GUI_SendKeyMsg(_ar_Key[1], 1);
				break;
			case WM_NOTIFICATION_RELEASED:
				break;
			}
			break;
			//5
		case ID_BUTTON_16: // Notifications sent by 'speedup_1'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_9);
				WM_SetFocus(hItem);
				EDIT_SetCursorAtChar(hItem, 3);
				GUI_SendKeyMsg(_ar_Key[0], 1);
				break;
			case WM_NOTIFICATION_RELEASED:
				break;
			}
			break;
		case ID_BUTTON_17: // Notifications sent by 'speeddown_1'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_9);
				WM_SetFocus(hItem);
				EDIT_SetCursorAtChar(hItem, 3);
				GUI_SendKeyMsg(_ar_Key[1], 1);
				break;
			case WM_NOTIFICATION_RELEASED:
				break;
			}
			break;
			//6
		case ID_BUTTON_20: // Notifications sent by 'speedup_1'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_11);
				WM_SetFocus(hItem);
				EDIT_SetCursorAtChar(hItem, 3);
				GUI_SendKeyMsg(_ar_Key[0], 1);
				break;
			case WM_NOTIFICATION_RELEASED:
				break;
			}
			break;
		case ID_BUTTON_21: // Notifications sent by 'speeddown_1'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_11);
				WM_SetFocus(hItem);
				EDIT_SetCursorAtChar(hItem, 3);
				GUI_SendKeyMsg(_ar_Key[1], 1);
				break;
			case WM_NOTIFICATION_RELEASED:
				break;
			}
			break;
			//7
		case ID_BUTTON_24: // Notifications sent by 'speedup_1'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_13);
				WM_SetFocus(hItem);
				EDIT_SetCursorAtChar(hItem, 3);
				GUI_SendKeyMsg(_ar_Key[0], 1);
				break;
			case WM_NOTIFICATION_RELEASED:
				break;
			}
			break;
		case ID_BUTTON_25: // Notifications sent by 'speeddown_1'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_13);
				WM_SetFocus(hItem);
				EDIT_SetCursorAtChar(hItem, 3);
				GUI_SendKeyMsg(_ar_Key[1], 1);
				break;
			case WM_NOTIFICATION_RELEASED:
				break;
			}
			break;

			/************BUTTON*************/

			/************chekBOX*************/
		case ID_CHECKBOX_0: // Notifications sent by 'fanzhuan_1'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_0));
				CHECKBOX_SetState(WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_1), 0);
				WM_EnableWindow(WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_1));
				break;
			case WM_NOTIFICATION_RELEASED:

				break;
			case WM_NOTIFICATION_VALUE_CHANGED:

				break;
			}

			break;

		case ID_CHECKBOX_1: // Notifications sent by 'zhengzhuan_1'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_1));
				CHECKBOX_SetState(WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_0), 0);
				WM_EnableWindow(WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_0));
				break;
			case WM_NOTIFICATION_RELEASED:

				break;
			case WM_NOTIFICATION_VALUE_CHANGED:

				break;

			}
			break;
		case ID_CHECKBOX_2: // Notifications sent by 'fanzhuan_1'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_2));
				CHECKBOX_SetState(WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_3), 0);
				WM_EnableWindow(WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_3));
				break;
			case WM_NOTIFICATION_RELEASED:

				break;
			case WM_NOTIFICATION_VALUE_CHANGED:

				break;
			}

			break;

		case ID_CHECKBOX_3: // Notifications sent by 'zhengzhuan_1'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_3));
				CHECKBOX_SetState(WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_2), 0);
				WM_EnableWindow(WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_2));
				break;
			case WM_NOTIFICATION_RELEASED:

				break;
			case WM_NOTIFICATION_VALUE_CHANGED:

				break;

			}
			break;

		case ID_CHECKBOX_4: // Notifications sent by 'fanzhuan_1'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_4));
				CHECKBOX_SetState(WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_5), 0);
				WM_EnableWindow(WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_5));
				break;
			case WM_NOTIFICATION_RELEASED:

				break;
			case WM_NOTIFICATION_VALUE_CHANGED:

				break;
			}

			break;

		case ID_CHECKBOX_5: // Notifications sent by 'zhengzhuan_1'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_5));
				CHECKBOX_SetState(WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_4), 0);
				WM_EnableWindow(WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_4));
				break;
			case WM_NOTIFICATION_RELEASED:

				break;
			case WM_NOTIFICATION_VALUE_CHANGED:

				break;

			}
			break;

		case ID_CHECKBOX_6: // Notifications sent by 'fanzhuan_1'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_6));
				CHECKBOX_SetState(WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_7), 0);
				WM_EnableWindow(WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_7));
				break;
			case WM_NOTIFICATION_RELEASED:

				break;
			case WM_NOTIFICATION_VALUE_CHANGED:

				break;
			}

			break;

		case ID_CHECKBOX_7: // Notifications sent by 'zhengzhuan_1'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_7));
				CHECKBOX_SetState(WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_6), 0);
				WM_EnableWindow(WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_6));
				break;
			case WM_NOTIFICATION_RELEASED:

				break;
			case WM_NOTIFICATION_VALUE_CHANGED:

				break;

			}
			break;

		case ID_CHECKBOX_8: // Notifications sent by 'fanzhuan_1'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_8));
				CHECKBOX_SetState(WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_9), 0);
				WM_EnableWindow(WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_9));
				break;
			case WM_NOTIFICATION_RELEASED:

				break;
			case WM_NOTIFICATION_VALUE_CHANGED:

				break;
			}

			break;

		case ID_CHECKBOX_9: // Notifications sent by 'zhengzhuan_1'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_9));
				CHECKBOX_SetState(WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_8), 0);
				WM_EnableWindow(WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_8));
				break;
			case WM_NOTIFICATION_RELEASED:

				break;
			case WM_NOTIFICATION_VALUE_CHANGED:

				break;

			}
			break;
		case ID_CHECKBOX_10: // Notifications sent by 'fanzhuan_1'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_10));
				CHECKBOX_SetState(WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_11), 0);
				WM_EnableWindow(WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_11));
				break;
			case WM_NOTIFICATION_RELEASED:

				break;
			case WM_NOTIFICATION_VALUE_CHANGED:

				break;
			}

			break;

		case ID_CHECKBOX_11: // Notifications sent by 'zhengzhuan_1'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_11));
				CHECKBOX_SetState(WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_10), 0);
				WM_EnableWindow(WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_10));
				break;
			case WM_NOTIFICATION_RELEASED:

				break;
			case WM_NOTIFICATION_VALUE_CHANGED:

				break;

			}
			break;

		case ID_CHECKBOX_12: // Notifications sent by 'fanzhuan_1'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_12));
				CHECKBOX_SetState(WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_13), 0);
				WM_EnableWindow(WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_13));
				break;
			case WM_NOTIFICATION_RELEASED:

				break;
			case WM_NOTIFICATION_VALUE_CHANGED:

				break;
			}

			break;

		case ID_CHECKBOX_13: // Notifications sent by 'zhengzhuan_1'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_13));
				CHECKBOX_SetState(WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_12), 0);
				WM_EnableWindow(WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_12));
				break;
			case WM_NOTIFICATION_RELEASED:

				break;
			case WM_NOTIFICATION_VALUE_CHANGED:

				break;

			}
			break;
     	/************chekBOX*************/
		}
		break;


		// USER Æô (Optionally insert additional message handling)
	case WM_PAINT:
		GUI_SetColor(GUI_BLACK); /* è®¾ç½®ç”»ç¬”é¢œè‰² */
		GUI_SetPenSize(1);
		// GUI_DrawPoint(250, 10);/*ç”»ç‚¹*/
		for (i = 0; i < 5; i++)
		{
			GUI_DrawLine(5 + Right_move_step*i, /* X èµ·å§‹ä½ç½® */85,/* Y èµ·å§‹ä½ç½® */155 + Right_move_step*i,/* X ç»“æŸä½ç½® */85);/* Y ç»“æŸä½ç½® */
			GUI_DrawLine(5 + Right_move_step*i, /* X èµ·å§‹ä½ç½® */85,/* Y èµ·å§‹ä½ç½® */5 + Right_move_step*i,/* X ç»“æŸä½ç½® */245);/* Y ç»“æŸä½ç½® */
			GUI_DrawLine(155 + Right_move_step*i, /* X èµ·å§‹ä½ç½® */85,/* Y èµ·å§‹ä½ç½® */155 + Right_move_step*i,/* X ç»“æŸä½ç½® */245);/* Y ç»“æŸä½ç½® */
			GUI_DrawLine(5 + Right_move_step*i, /* X èµ·å§‹ä½ç½® */245,/* Y èµ·å§‹ä½ç½® */155 + Right_move_step*i,/* X ç»“æŸä½ç½® */245);/* Y ç»“æŸä½ç½® */
		}
		for (i = 0; i < 2; i++)
		{
			GUI_DrawLine(5 + Right_move_step*i, /* X èµ·å§‹ä½ç½® */250,/* Y èµ·å§‹ä½ç½® */155 + Right_move_step*i,/* X ç»“æŸä½ç½® */250);/* Y ç»“æŸä½ç½® */
			GUI_DrawLine(5 + Right_move_step*i, /* X èµ·å§‹ä½ç½® */250,/* Y èµ·å§‹ä½ç½® */5 + Right_move_step*i,/* X ç»“æŸä½ç½® */415);/* Y ç»“æŸä½ç½® */
			GUI_DrawLine(155 + Right_move_step*i,/* X èµ·å§‹ä½ç½® */250,/* Y èµ·å§‹ä½ç½® */155 + Right_move_step*i,/* X ç»“æŸä½ç½® */415);/* Y ç»“æŸä½ç½® */
			GUI_DrawLine(5 + Right_move_step*i, /* X èµ·å§‹ä½ç½® */415,/* Y èµ·å§‹ä½ç½® */155 + Right_move_step*i,/* X ç»“æŸä½ç½® */415);/* Y ç»“æŸä½ç½® */
		}
		for (i = 2; i < 3; i++)
		{
			GUI_DrawLine(5 + Right_move_step*i, /* X èµ·å§‹ä½ç½® */250,/* Y èµ·å§‹ä½ç½® */155 + Right_move_step*i,/* X ç»“æŸä½ç½® */250);/* Y ç»“æŸä½ç½® */
			GUI_DrawLine(5 + Right_move_step*i, /* X èµ·å§‹ä½ç½® */250,/* Y èµ·å§‹ä½ç½® */5 + Right_move_step*i,/* X ç»“æŸä½ç½® */330);/* Y ç»“æŸä½ç½® */
			GUI_DrawLine(155 + Right_move_step*i,/* X èµ·å§‹ä½ç½® */250,/* Y èµ·å§‹ä½ç½® */155 + Right_move_step*i,/* X ç»“æŸä½ç½® */330);/* Y ç»“æŸä½ç½® */
			GUI_DrawLine(5 + Right_move_step*i, /* X èµ·å§‹ä½ç½® */330,/* Y èµ·å§‹ä½ç½® */155 + Right_move_step*i,/* X ç»“æŸä½ç½® */330);/* Y ç»“æŸä½ç½® */
		}
		for (i = 2; i < 3; i++)
		{
			GUI_DrawLine(5 + Right_move_step*i, /* X èµ·å§‹ä½ç½® */335,/* Y èµ·å§‹ä½ç½® */155 + Right_move_step*i,/* X ç»“æŸä½ç½® */335);/* Y ç»“æŸä½ç½® */
			GUI_DrawLine(5 + Right_move_step*i, /* X èµ·å§‹ä½ç½® */335,/* Y èµ·å§‹ä½ç½® */5 + Right_move_step*i,/* X ç»“æŸä½ç½® */415);/* Y ç»“æŸä½ç½® */
			GUI_DrawLine(155 + Right_move_step*i,/* X èµ·å§‹ä½ç½® */335,/* Y èµ·å§‹ä½ç½® */155 + Right_move_step*i,/* X ç»“æŸä½ç½® */415);/* Y ç»“æŸä½ç½® */
			GUI_DrawLine(5 + Right_move_step*i, /* X èµ·å§‹ä½ç½® */415,/* Y èµ·å§‹ä½ç½® */155 + Right_move_step*i,/* X ç»“æŸä½ç½® */415);/* Y ç»“æŸä½ç½® */
		}

		// USER END
		break;


	case ar_WM_switchSpeed:
		if (switchSpeed == 0)
		{
			for (i = 0; i < 13; i = i + 2){
				hItem = WM_GetDialogItem(pMsg->hWin, (GUI_ID_USER+0x3B+i) );
				EDIT_SetDecMode(hItem, 30, 0, 100, 0, 0);
			}
		}
		else if (switchSpeed == 1)
		{
			for (i = 0; i < 13; i = i + 2){
				hItem = WM_GetDialogItem(pMsg->hWin, (GUI_ID_USER + 0x3B + i));
				EDIT_SetDecMode(hItem, 60, 0, 100, 0, 0);
			}
		}
		else
		{
			for (i = 0; i < 13; i = i + 2){
				hItem = WM_GetDialogItem(pMsg->hWin, (GUI_ID_USER + 0x3B + i));
				EDIT_SetDecMode(hItem, 90, 0, 100, 0, 0);
			}
		}




		break;


	case ar_WM_fuwei:
//å¤ä½èµ·åœæŒ‰é’®
		WM_InvalidateWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2));
		WM_InvalidateWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3));
		WM_InvalidateWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_6));
		WM_InvalidateWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_7));
		WM_InvalidateWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_10));
		WM_InvalidateWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_11));
		WM_InvalidateWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_14));
		WM_InvalidateWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_15));
		WM_InvalidateWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_18));
		WM_InvalidateWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_19));
		WM_InvalidateWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_22));
		WM_InvalidateWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_23));
		WM_InvalidateWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_26));
		WM_InvalidateWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_27));
		WM_InvalidateWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_29));
		WM_InvalidateWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_30));
		WM_InvalidateWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_31));
		WM_InvalidateWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_32));
//å¤ä½ç”µæœºÕý×ª
		if (ar_fuwei_zhengfan == 1)
		{

			//1
			if (CHECKBOX_GetState(WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_0)) == 1){
				WM_EnableWindow(WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_0));
				hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_0);
				WM_SetFocus(hItem);
				GUI_SendKeyMsg(_ar_Key[2], 1);
			}
			if (CHECKBOX_GetState(WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_1)) == 0){
				hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_1);
				WM_SetFocus(hItem);
				GUI_SendKeyMsg(_ar_Key[2], 1);
				WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_1));
			}
			//2
			if (CHECKBOX_GetState(WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_2)) == 1){
				WM_EnableWindow(WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_2));
				hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_2);
				WM_SetFocus(hItem);
				GUI_SendKeyMsg(_ar_Key[2], 1);
			}
			if (CHECKBOX_GetState(WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_3)) == 0){
				hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_3);
				WM_SetFocus(hItem);
				GUI_SendKeyMsg(_ar_Key[2], 1);
				WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_3));
			}
			//3
			if (CHECKBOX_GetState(WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_4)) == 1){
				WM_EnableWindow(WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_4));
				hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_4);
				WM_SetFocus(hItem);
				GUI_SendKeyMsg(_ar_Key[2], 1);
			}
			if (CHECKBOX_GetState(WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_5)) == 0){
				hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_5);
				WM_SetFocus(hItem);
				GUI_SendKeyMsg(_ar_Key[2], 1);
				WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_5));
			}
			//4
			if (CHECKBOX_GetState(WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_6)) == 1){
				WM_EnableWindow(WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_6));
				hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_6);
				WM_SetFocus(hItem);
				GUI_SendKeyMsg(_ar_Key[2], 1);
			}
			if (CHECKBOX_GetState(WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_7)) == 0){
				hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_7);
				WM_SetFocus(hItem);
				GUI_SendKeyMsg(_ar_Key[2], 1);
				WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_7));
			}
			//5
			if (CHECKBOX_GetState(WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_8)) == 1){
				WM_EnableWindow(WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_8));
				hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_8);
				WM_SetFocus(hItem);
				GUI_SendKeyMsg(_ar_Key[2], 1);
			}
			if (CHECKBOX_GetState(WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_9)) == 0){
				hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_9);
				WM_SetFocus(hItem);
				GUI_SendKeyMsg(_ar_Key[2], 1);
				WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_9));
			}
			//6
			if (CHECKBOX_GetState(WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_10)) == 1){
				WM_EnableWindow(WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_10));
				hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_10);
				WM_SetFocus(hItem);
				GUI_SendKeyMsg(_ar_Key[2], 1);
			}
			if (CHECKBOX_GetState(WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_11)) == 0){
				hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_11);
				WM_SetFocus(hItem);
				GUI_SendKeyMsg(_ar_Key[2], 1);
				WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_11));
			}
			//7
			if (CHECKBOX_GetState(WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_12)) == 1){
				WM_EnableWindow(WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_12));
				hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_12);
				WM_SetFocus(hItem);
				GUI_SendKeyMsg(_ar_Key[2], 1);
			}
			if (CHECKBOX_GetState(WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_13)) == 0){
				hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_13);
				WM_SetFocus(hItem);
				GUI_SendKeyMsg(_ar_Key[2], 1);
				WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_13));
			}
		ar_fuwei_zhengfan = 0;
		}
		break;


		case ar_WM_zijian:
			putinDLG = Createar_putinNumber();

		


			//1-7ç”µæœºå¯åœ
			hItem = WM_GetDialogItem(pMsg->hWin, GUI_ID_USER + 0x09);
			WM_SetFocus(hItem);
			GUI_SendKeyMsg(_ar_Key[3], 1);
			GUI_Delay(700);
			hItem = WM_GetDialogItem(pMsg->hWin, GUI_ID_USER + 0x0A);
			WM_SetFocus(hItem);
			GUI_SendKeyMsg(_ar_Key[3], 1);

			for (i=0;i<41;i=i+8)
			{
				hItem = WM_GetDialogItem(pMsg->hWin, GUI_ID_USER + 0x0F+i);
				WM_SetFocus(hItem);
				GUI_SendKeyMsg(_ar_Key[3], 1);
				GUI_Delay(700);
				hItem = WM_GetDialogItem(pMsg->hWin, GUI_ID_USER + 0x10+i);
				WM_SetFocus(hItem);
				GUI_SendKeyMsg(_ar_Key[3], 1);
			}
           //1ï¼?æ°”ç¼¸ä¸Šä¸‹
			for (i = 0; i < 7; i = i + 3)
			{
				hItem = WM_GetDialogItem(pMsg->hWin, GUI_ID_USER + 0x51+i);
				WM_SetFocus(hItem);
				GUI_SendKeyMsg(_ar_Key[3], 1);
				GUI_Delay(700);
				hItem = WM_GetDialogItem(pMsg->hWin, GUI_ID_USER + 0x52+i);
				WM_SetFocus(hItem);
				GUI_SendKeyMsg(_ar_Key[3], 1);
			}




			GUI_EndDialog(putinDLG, 0);
			break;

		
	default:
		WM_DefaultProc(pMsg);
		break;
	}
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       Createar_MotorcontrolWindow
*/
WM_HWIN Createar_MotorcontrolWindow(void);
WM_HWIN Createar_MotorcontrolWindow(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(MotorcontrolWindow_aDialogCreate, GUI_COUNTOF(MotorcontrolWindow_aDialogCreate), MotorcontrolWindow_cbDialog, WM_HBKWIN, 0, 0);
  Createar_MotorcontrolALL(hWin);

  return hWin;
}

// USER Æô (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/

