/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.28                          *
*        Compiled Jan 30 2015, 16:41:06                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "includes.h"
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_FRAMEWIN_0 (GUI_ID_USER + 0x00)
#define ID_TEXT_0 (GUI_ID_USER + 0x01)
#define ID_TEXT_1 (GUI_ID_USER + 0x02)
#define ID_TEXT_2 (GUI_ID_USER + 0x03)
#define ID_EDIT_0 (GUI_ID_USER + 0x05)
#define ID_EDIT_1 (GUI_ID_USER + 0x06)
#define ID_TEXT_3 (GUI_ID_USER + 0x07)
#define ID_TEXT_4 (GUI_ID_USER + 0x08)
#define ID_EDIT_2 (GUI_ID_USER + 0x09)
#define ID_EDIT_3 (GUI_ID_USER + 0x0A)
#define ID_BUTTON_0 (GUI_ID_USER + 0x0B)
#define ID_BUTTON_1 (GUI_ID_USER + 0x0C)
#define ID_BUTTON_2 (GUI_ID_USER + 0x0D)
#define ID_TEXT_5 (GUI_ID_USER + 0x0E)
#define ID_TEXT_6 (GUI_ID_USER + 0x0F)
#define ID_DROPDOWN_0 (GUI_ID_USER + 0x10)

extern char ar_message;
// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO productioncontrol_aDialogCreate[] = {
  { FRAMEWIN_CreateIndirect, "ar_productioncontrol", ID_FRAMEWIN_0, 245, 250, 550, 225, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "生产模式", ID_TEXT_0, 0, 30, 100, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "目标产量", ID_TEXT_1, 0, 85, 100, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "当前产量", ID_TEXT_2, 0, 140, 100, 30, 0, 0x0, 0 },
  { EDIT_CreateIndirect, "taskEdit", ID_EDIT_0, 105, 85, 100, 30, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "yieldEdit", ID_EDIT_1, 105, 140, 100, 30, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "预计时间", ID_TEXT_3, 310, 85, 100, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "异常监测", ID_TEXT_4, 310, 140, 100, 30, 0, 0x0, 0 },
  { EDIT_CreateIndirect, "timeEdit", ID_EDIT_2, 415, 85, 100, 30, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "faultcountEdit", ID_EDIT_3, 415, 140, 100, 30, 0, 0x64, 0 },
  { BUTTON_CreateIndirect, "启动", ID_BUTTON_0, 280, 185, 80, 30, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "停止", ID_BUTTON_1, 420, 185, 80, 30, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, ":::", ID_BUTTON_2, 223, 30, 40, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "根", ID_TEXT_5, 215, 85, 24, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "根", ID_TEXT_6, 215, 140, 24, 30, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "mode", ID_DROPDOWN_0, 105, 30, 100, 120, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

 char psw_flag01 = 1;
/*
*********************************************************************
*
*       _cbButton0
*
**********************************************************************
*/
static void _cbButton0(WM_MESSAGE * pMsg) //--------------锛?锛?
{


	GUI_RECT Rect;


	switch (pMsg->MsgId)
	{
	case WM_PAINT:
		WM_GetClientRect(&Rect);

		if (psw_flag01 == 0)//if (BUTTON_IsPressed(hWin))
		{

			GUI_SetColor(GUI_GREEN);
			GUI_FillRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);
			GUI_SetBkColor(GUI_GREEN);

			GUI_SetColor(GUI_BLACK);
			GUI_SetPenSize(1);
			GUI_DrawRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);

			GUI_SetFont(&GUI_FontHZ24);
			GUI_DispStringInRect("启动", &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);

			WM_DisableWindow(WM_GetDialogItem(WM_GetParent(pMsg->hWin), ID_BUTTON_2));
			WM_DisableWindow(WM_GetDialogItem(WM_GetParent(pMsg->hWin), ID_DROPDOWN_0));

		}
		if (psw_flag01 != 0)
		{

			GUI_SetColor(GUI_LIGHTGRAY);
			GUI_FillRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);
			GUI_SetBkColor(GUI_LIGHTGRAY);

			GUI_SetColor(GUI_BLACK);
			GUI_SetPenSize(1);
			GUI_DrawRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);

			GUI_SetColor(GUI_BLACK);
			GUI_SetFont(&GUI_FontHZ24);
			GUI_DispStringInRect("启动", &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
		}


		break;
	default:
		BUTTON_Callback(pMsg);
	}
}

/*********************************************************************
*
*       _cbButton1
*
**********************************************************************
*/
static void _cbButton1(WM_MESSAGE * pMsg) //--------------锛?锛?
{

	GUI_RECT Rect;

	switch (pMsg->MsgId)
	{
	case WM_PAINT:
		WM_GetClientRect(&Rect);

		if (psw_flag01 == 1)
		{

			GUI_SetColor(GUI_RED);
			GUI_FillRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);
			GUI_SetBkColor(GUI_RED);

			GUI_SetColor(GUI_BLACK);
			GUI_SetPenSize(1);
			GUI_DrawRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);

			GUI_SetFont(&GUI_FontHZ24);
			GUI_DispStringInRect("停止", &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);

			WM_EnableWindow(WM_GetDialogItem(WM_GetParent(pMsg->hWin), ID_BUTTON_2));
			WM_EnableWindow(WM_GetDialogItem(WM_GetParent(pMsg->hWin), ID_DROPDOWN_0));

		}

		if (psw_flag01 != 1)
		{

			GUI_SetColor(GUI_GRAY);
			GUI_FillRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);
			GUI_SetBkColor(GUI_GRAY);

			GUI_SetColor(GUI_BLACK);
			GUI_SetPenSize(1);
			GUI_DrawRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);

			GUI_SetColor(GUI_BLACK);
			GUI_SetFont(&GUI_FontHZ24);
			GUI_DispStringInRect("停止", &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
		}

		break;
	default:
		BUTTON_Callback(pMsg);
	}
}
// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void productioncontrol_cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  static char Numpad_flag=1;
  static WM_HWIN hNumPad;
  static WM_HWIN putinDLG;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'ar_productioncontrol'
    //
    hItem = pMsg->hWin;
    FRAMEWIN_SetTitleVis(hItem, 0);
	
    //
    // Initialization of 'productionMode'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetFont(hItem, &GUI_FontHZ24);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'productionTask'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    TEXT_SetFont(hItem, &GUI_FontHZ24);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'yield'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetFont(hItem, &GUI_FontHZ24);
    //
    // Initialization of 'taskEdit'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
    EDIT_SetText(hItem, "123");
    EDIT_SetFont(hItem, GUI_FONT_24_ASCII);
    EDIT_SetTextAlign(hItem, GUI_TA_RIGHT | GUI_TA_VCENTER);
	WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, ID_EDIT_0));
    //
    // Initialization of 'yieldEdit'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_1);
    EDIT_SetText(hItem, "0");
    EDIT_SetFont(hItem, GUI_FONT_24_ASCII);
    EDIT_SetTextAlign(hItem, GUI_TA_RIGHT | GUI_TA_VCENTER);
	WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, ID_EDIT_1));
    //
    // Initialization of 'estimatedtime'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
    TEXT_SetFont(hItem, &GUI_FontHZ24);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'faultdetect'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);
    TEXT_SetFont(hItem, &GUI_FontHZ24);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'timeEdit'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_2);
    EDIT_SetText(hItem, "00:00:00");
    EDIT_SetFont(hItem, GUI_FONT_24_ASCII);
    EDIT_SetTextAlign(hItem, GUI_TA_RIGHT | GUI_TA_VCENTER);
	WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, ID_EDIT_2));
    //
    // Initialization of 'faultcountEdit'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_3);
    EDIT_SetText(hItem, "0");
    EDIT_SetFont(hItem, GUI_FONT_24_ASCII);
    EDIT_SetTextAlign(hItem, GUI_TA_RIGHT | GUI_TA_VCENTER);
	WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, ID_EDIT_3));
    //
    // Initialization of 'active'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    BUTTON_SetFont(hItem, &GUI_FontHZ24);
	WM_SetCallback(hItem, _cbButton0);
    //
    // Initialization of 'sstop'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
    BUTTON_SetFont(hItem, &GUI_FontHZ24);
	WM_SetCallback(hItem, _cbButton1);
    //
    // Initialization of '...'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
    BUTTON_SetFont(hItem, GUI_FONT_24_ASCII);
    //
    // Initialization of 'geng'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_5);
    TEXT_SetFont(hItem, &GUI_FontHZ24);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'geng2'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_6);
    TEXT_SetFont(hItem, &GUI_FontHZ24);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'mode'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_0);
    DROPDOWN_SetFont(hItem, &GUI_FontHZ24);
	DROPDOWN_SetAutoScroll(hItem, 1);
	
    DROPDOWN_AddString(hItem, "mode1");
    DROPDOWN_AddString(hItem, "mode2");
    DROPDOWN_AddString(hItem, "...");
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_EDIT_0: // Notifications sent by 'taskEdit'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_EDIT_1: // Notifications sent by 'yieldEdit'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_EDIT_2: // Notifications sent by 'timeEdit'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_EDIT_3: // Notifications sent by 'faultcountEdit'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_0: // Notifications sent by 'active'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
		  ar_message = 1;
		  WM_SendMessageNoPara(WM_GetParent(pMsg->hWin), ar_WM_message);

		  WM_InvalidateWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1));
		  psw_flag01 = 0;
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
						printf(" Active!");
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'sstop'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
		  ar_message = 2;
		  WM_SendMessageNoPara(WM_GetParent(pMsg->hWin), ar_WM_message);

		  WM_InvalidateWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0));
		  psw_flag01 = 1;
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
							printf(" Stop!");		
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_2: // Notifications sent by '...'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)

		  if (Numpad_flag == 1)
		  {
			  putinDLG = Createar_putinNumber();
			  hNumPad  = ar_NumpadCreat(WM_HBKWIN);
			  
			  WM_EnableWindow(WM_GetDialogItem(pMsg->hWin, ID_EDIT_0));
			  WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0));
			  WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1));
			  WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_0));


			  Numpad_flag = 0;
		  }
		  else
		  {
			  GUI_EndDialog(hNumPad, 0);
			  GUI_EndDialog(putinDLG, 0);
			  WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, ID_EDIT_0));
			  WM_EnableWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0));
			  WM_EnableWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1));
			  WM_EnableWindow(WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_0));

			  Numpad_flag = 1;
		  }
		 // WM_EnableWindow(WM_GetDialogItem(pMsg->hWin, ID_EDIT_0));
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		  ar_message = 0;
		  WM_SendMessageNoPara(WM_GetParent(pMsg->hWin), ar_WM_message);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_0: // Notifications sent by 'mode'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
	case WM_PAINT:
		GUI_SetColor(GUI_BLACK); /* 璁剧疆鐢荤瑪棰滆壊 */
		GUI_SetPenSize(1);
	
		//GUI_DrawLine(240, 80, 240, 170);
		break;
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       Createar_productioncontrol
*/
WM_HWIN Createar_productioncontrol(WM_HWIN hWiin);
WM_HWIN Createar_productioncontrol(WM_HWIN hWiin) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(productioncontrol_aDialogCreate, GUI_COUNTOF(productioncontrol_aDialogCreate), productioncontrol_cbDialog, hWiin, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
